# deployment.yaml (modificato)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-be-deployment
  labels:
    app: blog-be-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-be-app
  template:
    metadata:
      labels:
        app: blog-be-app
    spec:
      serviceAccountName: blog-be-sa
      containers:
        - name: blog-ai-aws-tunnel-mysql
          image: aws-image
          imagePullPolicy: Always
          env:
            - name: REMOTE_PORT
              value: "3306"
            - name: LOCAL_PORT
              value: "3306"
            - name: AWS_REGION
              value: "eu-west-1"
        - name: blog-be
          image: app-image
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: blog-be-config
